import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "../../globals.css";
import { Container } from "@/components/container";

//const inter = Inter({ weight: ["400", "500", "600", "700", "800", "900"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container className="min-h-screen px-10 md:pt-20 md:pb-10 prose">
        {children}
    </Container>
  );
}